### PR TITLE
Add radians and degrees

### PR DESCRIPTION
**Pull request by dfreiberger**
This PR adds support for the expressions `radians` and `degrees`, matching the expressions in Python's `math` module. 

These expressions are commonly found in various xacro files.

I have added unit tests as well which check that the expressions evaluate correctly. To handle potential floating point conversion errors, the tests evaluate expressions which should return an integer value.

Edit: I tried to squash the intermediate commits but wasn't successful, if you would prefer I do this to clean up history let me know. Also, most of the tests in `XacroLoader.test.js` don't actually run because of `it.only(` on `describe('comments`...) test. I'm not too familiar with javascript so maybe I am missing something. To verify the tests I added, I moved `it.only(` to the expression tests temporarily.

### CODE REVIEW

**Comment by gkjohnson** [comment]
Hi @dfreiberger! Somehow I missed this PR in my backlog of notifications. Thanks for the contribution I think this is a good addition. Do you have an example of any public xacro files that use `degrees` and `radians` functions?

> Also, most of the tests in XacroLoader.test.js don't actually run because of `it.only(` on `describe('comments...)` test.

Heh thanks for the catch. That's definitely from an accidental commit. I'll fix that in master.

**Comment by dfreiberger** [comment]
Hi @gkjohnson, thank you for adding this! I used your code to make a javascript viewer for a robot project, it worked great and has been really helpful. I may try to make a public project with a demo later.

Here is an example of an xacro file using radians:

https://github.com/ros-industrial/staubli_experimental/blob/ce422fe0a54232d73cf44e2571fc7abc2f5ff9f6/staubli_tx2_90_support/urdf/tx2_90_macro.xacro#L123

**Comment by gkjohnson** [comment]
(I've just reopened the PR because I haven't merged it, yet -- I expect it wasn't intentional you closed it).

Thanks for the example! 

> I used your code to make a javascript viewer for a robot project, it worked great and has been really helpful. I may try to make a public project with a demo later.

Glad to hear the project's been useful. I'm sure you've seen the [urdf-loaders](https://github.com/gkjohnson/urdf-loaders/tree/master/javascript) project, as well? I've been intending to update it to support dragging and dropping Xacro files, as well, but haven't found the time yet. I'd love to see a demo of your work when it's available -- I always  appreciate seeing how my projects are used.

Thank you again!

**Comment by gkjohnson** [comment]
Just published version v0.2.2 which includes the new `radians` and `degrees` support.

**Pull request merged**
